spring:
  jackson:
    default-property-inclusion: non-null
  hateoas:
    use-hal-as-default-json-media-type: false
  resources:
    cache:
      period: 31536000
      cachecontrol:
        max-age: 31536000
    chain:
      html-application-cache: true
      enabled: true
      strategy:
        content:
          enabled: true
          paths: /webjars/swagger-ui/**.*

springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    display-request-duration: true
    groups-order: ASC
